baseURL = "https://maknotavailable.github.io/jacqueskayser"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Dr. Jacques Kayser"

theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Google Analytics
googleAnalytics = "UA-71821549-1"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80
