  [[main]]
  name = "Accueil"
  identifier = "home"
  weight = 100
  url = "/fr/"

  [[main]]
  name = "Curriculum Vitae"
  weight = 400
  identifier = "cv"
  url = "/fr/cv/"

  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/fr/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/fr/imprint/"