
title = "Dr. Jacques Kayser"
author = "Jacques Kayser"
description = "Chirurgie viscérale"
profilePicture = "images/profile.jpg"
keywords = "Jacques Kayser"
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = [""]
images = [""]
doNotLoadAnimations = true

# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"

# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"
# relatedPosts = true
# numberOfRelatedPosts = 3

reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

hidesidebar = false

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/jacques-kayser-b184a46a/"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:viscerale@chirurgie-zitha.lu"

[[socialIcons]]
icon = "fas fa-hospital"
title = "Hospital"
url = "https://www.hopitauxschuman.lu/medecin/kayser-jacques/"

[[socialIcons]]
icon = "fas fa-map-location-dot"
title = "Address"
url = "https://goo.gl/maps/s87bLtPE8SAz3h3t7"